const galleryData = [
  { id: "1", imageName: "wrek1.jpg", tag: "wrek" },
  { id: "2", imageName: "wrek2.jpg", tag: "wrek" },
  { id: "3", imageName: "wrek3.jpg", tag: "wrek" },
  { id: "4", imageName: "wrek4.jpg", tag: "wrek" },
  { id: "5", imageName: "wrek5.jpg", tag: "wrek" },
  { id: "6", imageName: "wrek6.jpg", tag: "wrek" },
  { id: "7", imageName: "wrek7.jpg", tag: "wrek" },
  { id: "8", imageName: "wrek8.jpg", tag: "wrek" },
  { id: "9", imageName: "wrek9.jpg", tag: "wrek" },
  { id: "10", imageName: "wrek10.jpg", tag: "wrek" },
  { id: "11", imageName: "fish1.jpg", tag: "fish" },
  { id: "12", imageName: "fish2.jpg", tag: "fish" },
  { id: "13", imageName: "fish3.jpg", tag: "fish" },
  { id: "14", imageName: "fish4.jpg", tag: "fish" },
  { id: "15", imageName: "fish5.jpg", tag: "fish" },
  { id: "16", imageName: "fish6.jpg", tag: "fish" },
  { id: "17", imageName: "fish7.jpg", tag: "fish" },
  { id: "18", imageName: "fish8.jpg", tag: "fish" },
  { id: "19", imageName: "fish9.jpg", tag: "fish" },
  { id: "20", imageName: "fish10.jpg", tag: "fish" },
  { id: "21", imageName: "course1.jpg", tag: "course" },
  { id: "22", imageName: "course2.jpg", tag: "course" },
  { id: "23", imageName: "course3.jpg", tag: "course" },
  { id: "24", imageName: "course4.jpg", tag: "course" },
  { id: "25", imageName: "course5.jpg", tag: "course" },
  { id: "26", imageName: "course6.jpg", tag: "course" },
  { id: "27", imageName: "course7.jpg", tag: "course" },
  { id: "28", imageName: "course8.jpg", tag: "course" },
  { id: "29", imageName: "course9.jpg", tag: "course" },
  { id: "30", imageName: "course10.jpg", tag: "course" },
];
export default galleryData;
